#! /bin/bash

lex ast.l
yacc -d ast.y
gcc lex.yy.c y.tab.c -o ast.out
./ast.out

cd linker

lex label.l
gcc lex.yy.c -o linker.out
./linker.out

cd ../../xsm_expl;

./xsm -l library.lib -e ../stage3/ast.xsm